#!/bin/bash

TOOL_DIR=`dirname $0`
ROOT_DIR="${TOOL_DIR}/../"
FILES=( \ 
	'Classes' \ 
	'proj.android' \ 
	'README.md' \ 
	'LICENSE' \ 
	'CHANGES' \ 
)

for FILE in ${FILES[@]}; do
	echo -n "Check ${FILE}... "
	if [ -f ${ROOT_DIR}/${FILE} ]; then
		echo 'exists.'
	elif [ -d ${ROOT_DIR}/${FILE} ]; then
		echo 'exists.'
	else
		echo 'does NOT exist.'
		echo '[FATAL] Failed to verify package.'
		exit 1;
	fi
done

C_CLASSES=( \ 
	'GPEnvironment.h' \ 
	'GPJsonHelper.h' \ 
	'GPMacros.h' \ 
	'GrowthPush.h' \ 
	'ios/GPAppDelegateIntercepter.h' \ 
	'ios/GPAppDelegateIntercepter.m' \ 
	'ios/GPAppDelegateWrapper.h' \ 
	'ios/GPAppDelegateWrapperDelegate.h' \ 
	'ios/GrowthPushCCInternal.h' \ 
	'ios/GrowthPushCCInternal.m' \ 
	'ios/GrowthPush.mm' \ 
	'ios/UIApplication+GrowthPush.h' \ 
	'ios/UIApplication+GrowthPush.m' \ 
	'android/GrowthPush.cpp' \ 
)

for CLASS in ${C_CLASSES[@]}; do
	echo -n "Check ${CLASS}... "
	if [ -f ${ROOT_DIR}/Classes/GrowthPush/${CLASS} ]; then
		echo 'exists.'
	else
		echo 'does NOT exist.'
		echo '[FATAL] Failed to verify package.'
		exit 1;
	fi
done

JAVA_CLASSES=( \ 
	'com/growthpush/cocos2dx/Cocos2dxBridge.java' \ 
	'com/growthpush/cocos2dx/Cocos2dxBroadcastReceiver.java' \ 
	'com/growthpush/cocos2dx/GrowthPushJNI.java' \ 
)

for CLASS in ${JAVA_CLASSES[@]}; do
	echo -n "Check ${CLASS}... "
	if [ -f ${ROOT_DIR}/proj.android/src/${CLASS} ]; then
		echo 'exists.'
	else
		echo 'does NOT exist.'
		echo '[FATAL] Failed to verify package.'
		exit 1;
	fi
done

SUBMODULES=( \ 
	'growthpush-ios' \ 
	'growthpush-android' \ 
)

for SUBMODULE in ${SUBMODULES[@]}; do
	echo -n "Check submodule ${SUBMODULE}... "
	${ROOT_DIR}/submodules/${SUBMODULE}/tools/verify
	if [ $? -ne 0 ]; then
		echo 'does NOT exist.'
		echo '[FATAL] Failed to verify package.'
		exit 1;
	fi
done

echo '[SUCCESS] Completed to verify package.'
